modLoader="javafml"
loaderVersion="[4,)"
license="CC0-1.0"
issueTrackerURL="https://github.com/kestalkayden/weeping-creeper/issues"

[[mods]]
modId="weepingcreeper"
version="${version}"
displayName="Weeping Creeper"
description='''
Creepers that freeze when you look at them, move faster when you don't, and only damage players (not terrain) when they explode.
'''
authors="Kestalkayden"
displayURL="https://github.com/kestalkayden/weeping-creeper"

[[mixins]]
config="weepingcreeper.mixins.json"

[[dependencies.weepingcreeper]]
modId="neoforge"
type="required"
versionRange="[26.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.weepingcreeper]]
modId="minecraft"
type="required"
versionRange="[26.1,26.2)"
ordering="NONE"
side="BOTH"
